//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelaySend.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan Monday_Start {
            get {
                return ((global::System.TimeSpan)(this["Monday_Start"]));
            }
            set {
                this["Monday_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:30:00")]
        public global::System.TimeSpan Monday_End {
            get {
                return ((global::System.TimeSpan)(this["Monday_End"]));
            }
            set {
                this["Monday_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan Tuesday_Start {
            get {
                return ((global::System.TimeSpan)(this["Tuesday_Start"]));
            }
            set {
                this["Tuesday_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:30:00")]
        public global::System.TimeSpan Tuesday_End {
            get {
                return ((global::System.TimeSpan)(this["Tuesday_End"]));
            }
            set {
                this["Tuesday_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan Wednesday_Start {
            get {
                return ((global::System.TimeSpan)(this["Wednesday_Start"]));
            }
            set {
                this["Wednesday_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:30:00")]
        public global::System.TimeSpan Wednesday_End {
            get {
                return ((global::System.TimeSpan)(this["Wednesday_End"]));
            }
            set {
                this["Wednesday_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan Thursday_Start {
            get {
                return ((global::System.TimeSpan)(this["Thursday_Start"]));
            }
            set {
                this["Thursday_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:30:00")]
        public global::System.TimeSpan Thursday_End {
            get {
                return ((global::System.TimeSpan)(this["Thursday_End"]));
            }
            set {
                this["Thursday_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan Friday_Start {
            get {
                return ((global::System.TimeSpan)(this["Friday_Start"]));
            }
            set {
                this["Friday_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:30:00")]
        public global::System.TimeSpan Friday_End {
            get {
                return ((global::System.TimeSpan)(this["Friday_End"]));
            }
            set {
                this["Friday_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Saturday_Start {
            get {
                return ((global::System.TimeSpan)(this["Saturday_Start"]));
            }
            set {
                this["Saturday_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Saturday_End {
            get {
                return ((global::System.TimeSpan)(this["Saturday_End"]));
            }
            set {
                this["Saturday_End"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Sunday_Start {
            get {
                return ((global::System.TimeSpan)(this["Sunday_Start"]));
            }
            set {
                this["Sunday_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Sunday_End {
            get {
                return ((global::System.TimeSpan)(this["Sunday_End"]));
            }
            set {
                this["Sunday_End"] = value;
            }
        }
    }
}
